# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-14 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweeping', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='street',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='street',
            name='direction',
            field=models.CharField(choices=[('NS', 'North - South'), ('EW', 'East - West')], default='NS', max_length=10),
            preserve_default=False,
        ),
    ]
