# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 03:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sweeping', '0002_auto_20171114_0154'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='idk',
            new_name='Sweep',
        ),
    ]
