# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 03:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sweeping', '0003_auto_20171114_0342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sweep',
            old_name='from_adress',
            new_name='from_address',
        ),
        migrations.RenameField(
            model_name='sweep',
            old_name='meridian',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='sweep',
            old_name='to_adress',
            new_name='to_address',
        ),
        migrations.AlterField(
            model_name='sweep',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sweeping.Weekday'),
        ),
    ]
